const mongoose = require("mongoose");
const { Schema } = mongoose;
const { ObjectId } = Schema.Types;

const EventSchema = new Schema({
    _id: {
        type: ObjectId, // autogenerated from mongodb, not used directly
        required: true,
    },
    uuid: {
        type: String, // autogenerated unique identifier, used in API calls
        required: true,
        unique: true,
    },
    announcementId: {
        type: String, // uuid of the associated announcement
        ref: "Announcement",
    },
    title: {
        type: String,
        required: true,
    },
    type: {
        type: String, // general label for event
        required: true,
        enum: ["print session", "office hours", "lab closed", "other"],
        lowercase: true,
    },
    status: {
        type: String, // current status of the event
        required: true,
        enum: ["upcoming", "recurring"],
        lowercase: true,
    },
    description: {
        type: String, // detailed description of the event
    },
    createdBy: {
        type: String, // uuid of the user who created the event
        ref: "User",
        required: true,
    },
    dateCreated: {
        type: Date, // date the announcement was created
        required: true,
    },
    lastUpdatedBy: {
        type: String, // uuid of the user who last updated the announcement
        ref: "User",
        required: true,
    },
    dateLastUpdated: {
        type: Date, // date the announcement was last updated
        required: true,
    },
    isRecurring: { type: Boolean, default: true },
    date: { type: Date }, // for one-off events
    dayOfWeek: {
        type: String, // day of the week the event occurs on
        enum: [
            "Sunday",
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday",
        ],
    },
    startTime: {
        type: String, // start time in HH:mm format
        required: true,
    },
    endTime: {
        type: String, // end time in HH:mm format
        required: true,
    },
});

module.exports = Event = mongoose.model("events", EventSchema);
